## Practica lab13: Arroyo Muñoz Luz Carla

In [1]:
import pandas as pd

## Importacion de las librerias

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

import matplotlib.pyplot as plt

In [11]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay
)

In [13]:
##Carganmos el dataset Iris
from sklearn.datasets import load_iris
iris = load_iris(as_frame = True)

In [14]:
dfIris = iris.frame

In [15]:
dfIris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

## Exploracion del conjunto de datos

In [17]:
dfIris.shape

(150, 5)

In [18]:
dfIris.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [20]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [22]:
## renombrar la columna target a los nombres de las especies
dfIris.rename(columns = {"target": "especie"}, inplace = True)

In [23]:
dfIris["especie"] = dfIris["especie"].map({
    0: "setosa",
    1: "versicolor",
    2: "virginica"
})

In [24]:
dfIris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),especie
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [25]:
dfIris.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),especie
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

## Identificar variables predictoras (x) y las variables objetivo (y)

In [28]:
# variables predictoras
X = dfIris.drop(columns = ["especie"])

In [29]:
print("Variables predictoras")
print(X.columns)

Variables predictoras
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [31]:
# variables objetivo
y = dfIris["especie"]

In [32]:
print("Variables objetivo")
print(y.name)

Variables objetivo
especie

## Dividir los datos en prueba y entrenamiento

80% para entrenamiento
20% para prueba

In [33]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.20, random_state = 42, stratify = y 
)

In [35]:
print("X_train", X_train.shape)
print("X_test", X_test.shape)
print("y_train", y_train.shape)
print("y_test", y_test.shape)

X_train (120, 4)
X_test (30, 4)
y_train (120,)
y_test (30,)

## Escalado de variables

In [37]:
scaler = StandardScaler()

In [38]:
# escalamos las variables
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)

In [40]:
print("sin escalar")
print(X_train.head())
print("escalado")
print(X_train_scaler[:5])

sin escalar
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
8                  4.4               2.9                1.4               0.2
106                4.9               2.5                4.5               1.7
76                 6.8               2.8                4.8               1.4
9                  4.9               3.1                1.5               0.1
89                 5.5               2.5                4.0               1.3
escalado
[[-1.72156775 -0.33210111 -1.34572231 -1.32327558]
 [-1.12449223 -1.22765467  0.41450518  0.6517626 ]
 [ 1.14439475 -0.5559895   0.58484978  0.25675496]
 [-1.12449223  0.11567567 -1.28894078 -1.45494479]
 [-0.40800161 -1.22765467  0.13059752  0.12508575]]

## Entrenamiento del modelo de KNN

En esta prueba utilizaremos el modelo de k = 3

In [41]:
modelo = KNeighborsClassifier(n_neighbors = 3)

In [42]:
modelo.fit(
    X_train_scaler, y_train
)

KNeighborsClassifier(n_neighbors=3)

## Realizamos predicciones con las variables de prueba

In [43]:
prediccion = modelo.predict(X_test_scaler)

In [44]:
print(prediccion[:10])

['setosa' 'virginica' 'versicolor' 'versicolor' 'setosa' 'versicolor'
 'setosa' 'setosa' 'virginica' 'versicolor']

In [45]:
# Comparacion entre valores reales y valores predecibles
comparacion = pd.DataFrame({
    "especie real": y_test.values,
    "especie pre-dicha": prediccion
})

In [46]:
comparacion.head(10)

  especie real especie pre-dicha
0       setosa            setosa
1    virginica         virginica
2   versicolor        versicolor
3   versicolor        versicolor
4       setosa            setosa
5   versicolor        versicolor
6       setosa            setosa
7       setosa            setosa
8    virginica         virginica
9   versicolor        versicolor

## Evaluacion del modelo

In [47]:
accuracy = accuracy_score(y_test, prediccion)
print (f"accuracy/exactitud: {accuracy: .4f}")

accuracy/exactitud:  0.9333

In [48]:
# matriz de confucion -- igual en los modelos de la tarea

cm = confusion_matrix(y_test, prediccion)

In [50]:
cm_df = pd.DataFrame(
    cm,
    index = modelo.classes_,
    columns = modelo.classes_
)
cm_df

            setosa  versicolor  virginica
setosa          10           0          0
versicolor       0          10          0
virginica        0           2          8

## CLASIFICATION REPORT

PROPORCIONA METRICAS QUE PERMITE EVALUAR EL DESEMPEÑO DE CADA CLASE: PRECISION, RECALL, F1_SCORE AND SUPORT

In [52]:
print(classification_report(y_test, prediccion))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.83      1.00      0.91        10
   virginica       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30